Collapsible form (#28)
* Add accordion component

* Use accordion component in config form

* Description + input on one line

* Also zen space the close button on permutation form

* Stop lastpass plugin from filling out the name field

* pnpm add @modular-forms/solid

* Use modularforms field component - not working yet due to
ReferenceError: React is not defined

* try fix react error by using vite-plugin-solid

* Wrap textfield in modularforms field tag; now state is preserved; TODO fix submit button

* Use modularforms submithandler, but only the expanded section of the accordion is parsed

* dirty commit; store has all changed values, but when you edit the config a new form with a new store is created; must re-initialize with previous values

* initialize new form with previous values + use shouldDirty to get rid of empty strings in output, for they mess up the way zod parses the config

* Remnants

* Remove vite plugin

* Remove debug statements

* Add whitespace

---------

Co-authored-by: sverhoeven <s.verhoeven@esciencecenter.nl>